import {test} from 'node:test';
import assert from 'node:assert/strict';
import {adminEnvironment,plain} from './helpers/admin-environment.mjs';
const dataset=()=>({classes:[{id:'a',name:'A',students:[{email:'a@x',name:'02 B',number:'2'},{email:'b@x',name:'01 A',number:'1'},{email:'c@x',name:'03 C',number:''}]},{id:'b',name:'B',students:[{email:'d@x',name:'D',number:'1'}]}],responses:[{id:'r1',courseId:'a',email:'a@x',date:'2026-09-24',submitted:'2026-09-24',fingerprint:'f1',fields:{評価:'0'}},{id:'r2',courseId:'b',email:'d@x',date:'2026-09-25',fingerprint:'f2',fields:{評価:'A'}}],headers:['評価'],issues:[]});
function setup(){const {c}=adminEnvironment();return {c,base:{classIds:[],start:'',end:'',dateHeader:'授業日',valueHeader:'評価',leading:['roster:number','roster:name'],sort:'name',mapping:{}},rules:{dates:[],answers:[],duplicates:[],fields:[]}};}
test('export keeps the whole roster and separates class calendars and zero from missing',()=>{const {c,base,rules}=setup();const out=plain(c.gradeBuild_(dataset(),{base,rules,calendar:[]}));assert.equal(out.issues.length,0);assert.deepEqual(out.classes[0].rows,[['出席番号','名前','2026/09/24'],['1','01 A',''],['2','02 B','0'],['','03 C','']]);assert.equal(out.classes[1].rows[0][2],'2026/09/25');});
test('ICS unmatched dates require a decision; planned and extra decisions place columns correctly',()=>{const {c,base,rules}=setup();base.classIds=['a'];base.mapping.a='授業A';const calendar=[{id:'e1',title:'授業A',date:'2026-09-28',time:'09:00'}];let out=c.gradeBuild_(dataset(),{base,rules,calendar});assert.equal(out.issues[0].type,'date');rules.dates=[{courseId:'a',from:'2026-09-24',mode:'extra',to:'2026-09-24'}];out=c.gradeBuild_(dataset(),{base,rules,calendar});assert.deepEqual(plain(out.classes[0].rows[0]),['出席番号','名前','2026/09/28','2026/09/24（予定外）']);rules.dates[0].mode='planned';out=c.gradeBuild_(dataset(),{base,rules,calendar});assert.deepEqual(plain(out.classes[0].rows[0]),['出席番号','名前','2026/09/24','2026/09/28']);});
test('date correction happens before duplicate detection; explicit slots preserve two lessons',()=>{const {c,base,rules}=setup(),d=dataset();base.classIds=['a'];d.responses.push({...d.responses[0],id:'r3',date:'2026-09-25',fingerprint:'f3',fields:{評価:'B'}});rules.dates=[{courseId:'a',from:'2026-09-25',to:'2026-09-24',mode:'planned'}];let out=c.gradeBuild_(d,{base,rules,calendar:[]});const issue=out.issues.find(i=>i.type==='duplicate');assert.ok(issue);rules.duplicates=[{key:issue.key,fingerprint:issue.fingerprint,assignments:{r1:1,r3:2}}];out=c.gradeBuild_(d,{base,rules,calendar:[]});assert.equal(out.issues.length,0);assert.deepEqual(plain(out.classes[0].rows[2]),['2','02 B','0','B']);d.responses.push({...d.responses[0],id:'r4',fingerprint:'f4'});assert.ok(c.gradeBuild_(d,{base,rules,calendar:[]}).issues.some(i=>i.type==='duplicate'));});
test('missing dates and unknown roster members cannot silently disappear',()=>{const {c,base,rules}=setup(),d=dataset();d.responses[0].date='';assert.ok(c.gradeBuild_(d,{base,rules,calendar:[]}).issues.some(i=>i.type==='date'));d.responses[0].email='unknown@x';assert.ok(c.gradeBuild_(d,{base,rules,calendar:[]}).issues.some(i=>i.type==='roster'));});
test('ICS unfolds titles, reads floating school time, rejects unsupported recurrence',()=>{const {c}=setup();const s='BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:a\r\nSUMMARY:生物\r\n 基礎(1)\r\nDTSTART:20260924T094000\r\nEND:VEVENT\r\nEND:VCALENDAR';assert.deepEqual(plain(c.gradeParseIcs_(s)),[{id:'a',title:'生物基礎(1)',date:'2026-09-24',time:'09:40'}]);assert.throws(()=>c.gradeParseIcs_(s.replace('END:VEVENT','RRULE:FREQ=WEEKLY\r\nEND:VEVENT')),/繰り返し|対応/);});
test('CSV contains BOM, quotes multiline fields and preserves zero',()=>{const {c}=setup();assert.equal(c.gradeCsv_([['名前','評価'],['山田,"太郎"','A\nB'],['0','']]),'\ufeff名前,評価\r\n"山田,""太郎""","A\nB"\r\n0,\r\n');});
test('grade settings reject invalid dates, columns and malicious shapes',()=>{const {c,base,rules}=setup();assert.throws(()=>c.gradeValidate_({base:{...base,start:'2026-02-30'},rules,calendar:[]}),/日付/);assert.throws(()=>c.gradeValidate_({base:{...base,leading:['bad']},rules,calendar:[]}),/列/);assert.throws(()=>c.gradeValidate_(JSON.parse('{"__proto__":{}}')),/形式|項目/);});
test('split storage keeps committed version when the next write fails',()=>{const h=adminEnvironment(),c=h.c;c.ScriptApp.getScriptId=()=> 'script';c.gradeWriteStore_({draft:c.gradeDefault_(),presets:[]},'');const old=c.gradeReadStore_();const s=h.ss.getSheetByName('システム管理');let count=0;s.beforeWrite=()=>{if(++count===2)throw Error('disk fail');};assert.throws(()=>c.gradeWriteStore_({draft:c.gradeDefault_(),presets:[{id:'x',name:'new',profile:c.gradeDefault_()}]},old.revision),/disk fail/);assert.equal(c.gradeReadStore_().revision,old.revision);assert.equal(c.gradeReadStore_().value.presets.length,0);});
test('storage refuses stale save revisions',()=>{const h=adminEnvironment(),c=h.c;c.ScriptApp.getScriptId=()=> 'script';c.gradeWriteStore_({draft:c.gradeDefault_(),presets:[]},'');assert.throws(()=>c.gradeWriteStore_({draft:c.gradeDefault_(),presets:[]},''),/変更|競合/);});
test('preview revision is independent of RPC object property ordering',()=>{
 const {c,base,rules}=setup();c.assertWebOperator_=()=>{};c.gradeReadData_=()=>dataset();const p={base,rules,calendar:[]};const reverse=x=>Array.isArray(x)?x.map(reverse):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).reverse().map(k=>[k,reverse(x[k])])):x;
 assert.equal(c.gradePreview(p).revision,c.gradePreview(reverse(p)).revision);
});
